marker_map:
  1: [3, 9.000, -1.5708]
  2: [6, 7.400,  3.1416]     
  3: [0, 7.410, 3.1416, 0]       
  4: [6, 4.5, 3.1416]       
  5: [0, 4.500, 0]
  6: [6, 2.720, 3.1416]
  7: [0, 2.720, 0]
  8: [6, 0, 1.5708]
  9: [3, 0, 1.5708]
  10: [0, 0, 1.5708]